UPDATE technicians SET specialty = 'Engine performance', status = CASE WHEN status = 'UNAVAILABLE' THEN status ELSE 'IN_BAY' END, territory = 'ROOFTOP_01', skills_json = '["engine","drivability","electrical"]', parts_json = '["CKP-39180-2M100","PAD-FRT-G80"]' WHERE id = 'T-147';
UPDATE technicians SET specialty = 'Electrical & ADAS', status = CASE WHEN status = 'UNAVAILABLE' THEN status ELSE 'ROAD_TEST' END, territory = 'ROOFTOP_01', skills_json = '["electrical","adas","maintenance"]', parts_json = '["CAM-ADAS-GV60"]' WHERE id = 'T-208';
UPDATE technicians SET specialty = 'Drivability', status = CASE WHEN status = 'UNAVAILABLE' THEN status ELSE 'IN_BAY' END, territory = 'ROOFTOP_01', skills_json = '["drivability","engine","maintenance"]', parts_json = '["CKP-39180-2M100","THERM-G90"]' WHERE id = 'T-274';
UPDATE technicians SET specialty = 'Master technician', status = CASE WHEN status = 'UNAVAILABLE' THEN status ELSE 'IN_BAY' END, territory = 'ROOFTOP_01', skills_json = '["engine","drivability","brakes","electrical","adas","maintenance"]', parts_json = '["CKP-39180-2M100","PAD-FRT-G80","CAM-ADAS-GV60","THERM-G90"]' WHERE id = 'T-319';
--> statement-breakpoint
UPDATE work_orders SET appliance = 'Check-engine diagnosis', city = '2023 GV70', appointment_window = '11:00 AM', required_skill = 'drivability', part_code = 'CKP-39180-2M100' WHERE id = 'WO-48321';
UPDATE work_orders SET appliance = 'Brake vibration', city = '2022 G80', appointment_window = '1:00 PM', required_skill = 'brakes', part_code = 'PAD-FRT-G80' WHERE id = 'WO-48344';
UPDATE work_orders SET appliance = '60K maintenance', city = '2021 GV80', appointment_window = '3:00 PM', required_skill = 'maintenance', part_code = NULL WHERE id = 'WO-48367';
UPDATE work_orders SET appliance = 'Intermittent no-start', city = '2023 G70', appointment_window = '3:30 PM', required_skill = 'drivability', part_code = 'CKP-39180-2M100' WHERE id = 'WO-48372';
UPDATE work_orders SET appliance = 'Recall campaign', city = '2024 GV80', appointment_window = '4:00 PM', required_skill = 'engine', part_code = NULL WHERE id = 'WO-48389';
UPDATE work_orders SET appliance = 'ADAS calibration', city = '2023 GV60', appointment_window = '2:00 PM', required_skill = 'adas', part_code = 'CAM-ADAS-GV60' WHERE id = 'WO-48401';
UPDATE work_orders SET appliance = 'Cooling-system repair', city = '2022 G90', appointment_window = '4:30 PM', required_skill = 'engine', part_code = 'THERM-G90' WHERE id = 'WO-48412';
UPDATE work_orders SET appliance = 'Intermittent no-start', city = '2023 G70 2.5T', appointment_window = 'Promise 3:30 PM', required_skill = 'drivability', part_code = 'CKP-39180-2M100' WHERE id = 'WO-48509';
--> statement-breakpoint
UPDATE diagnostic_cases SET appliance_make = 'Genesis', appliance_model = 'G70 2.5T', serial_tail = '4H27', complaint = 'Intermittent no-start after hot soak. Engine cranks normally, P0335 is stored, and engine-speed data drops out during the event.', symptom_code = 'HOT_SOAK_NO_START_P0335' WHERE id = 'DC-48509';
UPDATE diagnostic_sources SET title = 'P0335 diagnostic procedure', appliance_make = 'Genesis', appliance_model = 'G70 2.5T', reference_code = 'PROC-G70-P0335', summary = 'Portfolio reference fixture covering crank signal capture, circuit integrity, connector inspection, and starting-system verification.' WHERE id = 'DS-PROC-204';
UPDATE diagnostic_sources SET title = 'Hot-soak no-start diagnostic bulletin', appliance_make = 'Genesis', appliance_model = 'G70 2.5T', reference_code = 'TSB-G70-042', summary = 'Portfolio reference fixture separating intermittent crank signal, ECM supply, and starter-circuit faults.' WHERE id = 'DS-BULLETIN-042';
UPDATE diagnostic_sources SET appliance_make = 'Genesis', appliance_model = 'G70 2.5T', reference_code = 'HIST-G70-117', summary = 'Synthetic outcome set for 117 comparable repair orders, weighted by verified first-time fixes.' WHERE id = 'DS-HISTORY-117';
UPDATE diagnostic_sources SET title = 'High-current electrical safety policy', reference_code = 'SAFE-ELEC-001', summary = 'Portfolio safety policy requiring vehicle securement, electrical isolation, and technician acknowledgement before protected tests.' WHERE id = 'DS-SAFETY-001';
--> statement-breakpoint
UPDATE diagnostic_recommendations SET fault_code = 'CKP_SIGNAL_DROPOUT', component = 'Crankshaft position sensor circuit', confidence = 72, rationale = 'The hot-soak no-start, stored P0335, and tachometer signal dropout align with an intermittent crankshaft position signal. Comparable verified repairs support circuit testing before component replacement.', verification_step = 'Follow the OEM procedure to reproduce the hot-soak condition, capture crank and cam signals, then inspect sensor power, ground, connector tension, and harness routing.', part_code = 'CKP-39180-2M100' WHERE case_id = 'DC-48509' AND rank = 1;
UPDATE diagnostic_recommendations SET fault_code = 'ECM_POWER_GROUND', component = 'ECM power and ground integrity', confidence = 18, rationale = 'A transient ECM supply or ground fault can produce the same loss of engine-speed signal, but the available case evidence gives it less support than the sensor circuit.', verification_step = 'Use the approved breakout procedure to perform loaded voltage-drop checks at ECM power and ground points while monitoring the fault event.', part_code = NULL WHERE case_id = 'DC-48509' AND rank = 2;
UPDATE diagnostic_recommendations SET fault_code = 'STARTER_VOLTAGE_DROP', component = 'Starter circuit voltage drop', confidence = 7, rationale = 'A heat-sensitive starter or high-resistance connection remains possible, but it does not explain the stored crankshaft signal fault as well as the higher-ranked paths.', verification_step = 'Escalate for high-current starting-system testing if crank signal and ECM integrity checks pass. Do not replace the starter from symptom matching alone.', part_code = 'STRTR-G70-25T' WHERE case_id = 'DC-48509' AND rank = 3;
UPDATE diagnostic_outcomes SET notes = 'Verified intermittent crank-sensor signal dropout, completed the repair, and confirmed reliable hot restart.' WHERE case_id = 'DC-48509';
--> statement-breakpoint
UPDATE parts_inventory SET part_code = 'CKP-39180-2M100', description = 'Crankshaft position sensor', location = 'Parts department', on_hand = 3, reserved = 1 WHERE id = 'PI-FAN-MAN';
UPDATE parts_inventory SET part_code = 'CKP-39180-2M100', description = 'Crankshaft position sensor', location = 'Regional PDC', on_hand = 2, reserved = 0 WHERE id = 'PI-FAN-NAS';
UPDATE parts_inventory SET part_code = 'HARNESS-G70-CKP', description = 'Crank sensor repair harness', location = 'Parts department', on_hand = 2, reserved = 1 WHERE id = 'PI-SENSOR-MAN';
UPDATE parts_inventory SET part_code = 'HARNESS-G70-CKP', description = 'Crank sensor repair harness', location = 'Diagnostic tool room', on_hand = 1, reserved = 0 WHERE id = 'PI-SENSOR-VAN';
UPDATE parts_inventory SET part_code = 'STRTR-G70-25T', description = 'Starter motor assembly', location = 'Regional PDC', on_hand = 1, reserved = 1 WHERE id = 'PI-PCB-MAN';
--> statement-breakpoint
UPDATE ai_agents SET name = 'Shop Load Agent', responsibility = 'Repair-order assignment and technician capacity recovery', owner_team = 'Service Technology' WHERE id = 'dispatch';
UPDATE ai_agents SET name = 'Promise Recovery Agent', responsibility = 'Same-day promise protection and exception handling', owner_team = 'Fixed Operations' WHERE id = 'recovery';
UPDATE ai_agents SET responsibility = 'Inventory validation and parts-counter availability', owner_team = 'Parts Operations' WHERE id = 'parts';
UPDATE ai_agents SET name = 'Advisor Communication Agent', responsibility = 'Bounded promise-time and delay notifications', owner_team = 'Service Experience' WHERE id = 'communications';
UPDATE agent_versions SET tools_json = '["shop_load_optimizer","technician_directory","policy_engine"]', permissions_json = '["read_repair_orders","propose_assignments"]' WHERE id = 'dispatch-v2.4.0';
UPDATE agent_versions SET tools_json = '["shop_load_optimizer","technician_directory","policy_engine","event_stream"]', permissions_json = '["read_repair_orders","propose_assignments"]' WHERE id = 'dispatch-v2.5.0';
UPDATE agent_versions SET tools_json = '["impact_analyzer","shop_load_optimizer","policy_engine"]', permissions_json = '["read_repair_orders","propose_recovery"]' WHERE id = 'recovery-v1.8.2';
UPDATE agent_versions SET tools_json = '["impact_analyzer","shop_load_optimizer","policy_engine","promise_time"]', permissions_json = '["read_repair_orders","propose_recovery"]' WHERE id = 'recovery-v1.9.0';
UPDATE benchmark_results SET label = CASE profile_key WHEN 'small' THEN 'Single rooftop' WHEN 'regional' THEN 'Regional dealer group' WHEN 'enterprise' THEN 'Enterprise dealer group' WHEN 'peak' THEN 'Peak service load' ELSE label END;
