"use client";
import { useEffect,useMemo,useState } from "react";
import { Activity,AlertTriangle,ArrowRight,BrainCircuit,Check,ChevronDown,CircleDot,Clock3,Gauge,Map,Menu,MoreHorizontal,Navigation,Route,Search,Settings2,ShieldCheck,Sparkles,Users,X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Slider } from "@/components/ui/slider";
import { defaultPolicyWeights,optimizeRecovery,type PolicyWeights,type RecoveryPlan } from "@/lib/dispatch-optimizer";
type Technician={id:string;initials:string;name:string;specialty:string;stops:number;miles:number;utilization:number;status:"On route"|"At service"|"Available";color:string};
const technicians:Technician[]=[
{id:"T-147",initials:"DM",name:"Darius Miles",specialty:"Refrigeration",stops:6,miles:42.8,utilization:86,status:"At service",color:"#ee6b45"},
{id:"T-208",initials:"SC",name:"Sofia Chen",specialty:"Laundry",stops:7,miles:36.2,utilization:91,status:"On route",color:"#b78cff"},
{id:"T-274",initials:"JR",name:"Jonah Reed",specialty:"Cooking",stops:5,miles:31.4,utilization:74,status:"On route",color:"#4ad1a8"},
{id:"T-319",initials:"AP",name:"Amara Patel",specialty:"Multi-skill",stops:7,miles:39.1,utilization:94,status:"At service",color:"#f5bd4f"}];
const navItems=[[Gauge,"Command"],[Map,"Live map"],[Route,"Routes"],[Users,"Technicians"],[Activity,"Performance"]] as const;
function Metric({label,value,detail,trend}:{label:string;value:string;detail:string;trend?:string}){return <div className="metric-card"><div className="metric-label">{label}</div><div className="metric-row"><strong>{value}</strong>{trend&&<span className="trend">{trend}</span>}</div><span className="metric-detail">{detail}</span></div>}
export default function Home(){
const [selected,setSelected]=useState("Command"),[incident,setIncident]=useState(false),[resolved,setResolved]=useState(false),[reviewOpen,setReviewOpen]=useState(false),[policyOpen,setPolicyOpen]=useState(false),[weights,setWeights]=useState<PolicyWeights>(defaultPolicyWeights),[search,setSearch]=useState(""),[mobileNav,setMobileNav]=useState(false);
const visible=useMemo(()=>technicians.filter(t=>`${t.name} ${t.id} ${t.specialty}`.toLowerCase().includes(search.toLowerCase())),[search]);
const plan=useMemo(()=>optimizeRecovery(weights),[weights]);
const accept=()=>{setReviewOpen(false);setIncident(false);setResolved(true);window.setTimeout(()=>setResolved(false),4200)};
useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  void Promise.resolve(context.registerTool({name:"simulate_dispatch_disruption",title:"Simulate dispatch disruption",description:"Simulate a technician becoming unavailable and display the operational impact in the command center.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{setIncident(true);setResolved(false);return {status:"simulated",affectedStops:7,technicianId:"T-274"}}},{signal:lifecycle.signal})).catch(()=>undefined);
  void Promise.resolve(context.registerTool({name:"update_dispatch_policy",title:"Update dispatch policy",description:"Set all five optimization weights and recalculate the best feasible recovery plan.",inputSchema:{type:"object",properties:{sla:{type:"number",minimum:0,maximum:60},travel:{type:"number",minimum:0,maximum:60},load:{type:"number",minimum:0,maximum:60},overtime:{type:"number",minimum:0,maximum:60},stability:{type:"number",minimum:0,maximum:60}},required:["sla","travel","load","overtime","stability"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const next=input as PolicyWeights;setWeights(next);const result=optimizeRecovery(next);return {status:"recalculated",score:result.score,projectedSla:result.projectedSla,assignments:result.assignments.length,rescheduled:result.rescheduled.length}}},{signal:lifecycle.signal})).catch(()=>undefined);
  void Promise.resolve(context.registerTool({name:"execute_recovery_plan",title:"Execute recovery plan",description:"Accept the current recovery plan and update the visible dispatch operation.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{setReviewOpen(false);setIncident(false);setResolved(true);return {status:"executed",routesUpdated:3,customersQueued:2}}},{signal:lifecycle.signal})).catch(()=>undefined);
  return()=>lifecycle.abort();
},[]);
return <main className="app-shell"><aside className={`sidebar ${mobileNav?"sidebar-open":""}`}>
<div className="brand"><span className="brand-mark"><Route size={18}/></span><span>FieldOps<span>AI</span></span></div><button className="mobile-close" aria-label="Close navigation" onClick={()=>setMobileNav(false)}><X/></button>
<nav aria-label="Main navigation"><p>Operations</p>{navItems.map(([Icon,label])=><button key={label} onClick={()=>{setSelected(label);setMobileNav(false)}} className={selected===label?"active":""}><Icon/><span>{label}</span>{label==="Routes"&&<small>25</small>}</button>)}</nav>
<div className="system-card"><div><ShieldCheck/><span>Orchestrator</span></div><strong>All systems nominal</strong><p>Last decision 14 sec ago</p></div><div className="profile"><span>MP</span><div><strong>Michael Palmer</strong><small>Operations lead</small></div><MoreHorizontal/></div></aside>
<section className="workspace"><header className="topbar"><button className="menu-button" onClick={()=>setMobileNav(true)} aria-label="Open navigation"><Menu/></button><div><h1>Dispatch command</h1><p>Greater Boston service territory</p></div><div className="topbar-actions"><div className="operating"><CircleDot/> Live operation <ChevronDown/></div><span className="date">Friday, Sep 12</span><Button variant="outline" onClick={()=>setPolicyOpen(true)} className="policy-button"><Settings2/> Policy controls</Button><Button onClick={()=>{setIncident(true);setResolved(false)}} className="simulate"><Sparkles/> Simulate disruption</Button></div></header>
<div className="content">{resolved&&<div className="success-banner"><Check/> Recovery plan accepted. Three routes updated and customers queued for notification.</div>}
<section className="metrics" aria-label="Today's performance"><Metric label="SLA achievement" value={incident?"91.6%":"94.1%"} detail="Target 92.0%" trend={incident?"−2.5%":"+1.8%"}/><Metric label="Active routes" value="25" detail="27 technicians available"/><Metric label="Travel distance" value={incident?"386 mi":"351 mi"} detail="Baseline 423 mi" trend={incident?"+10.0%":"−17.0%"}/><Metric label="At-risk stops" value={incident?"7":"2"} detail={incident?"Action required":"Within recovery range"}/></section>
<section className="operations-grid"><article className="panel map-panel"><div className="panel-heading"><div><h2>Live territory</h2><p>25 routes · 164 scheduled stops</p></div><div className="map-key"><span><i/> On route</span><span><i className="service-dot"/> At service</span></div></div><div className="map-surface"><div className="map-grid"/><svg viewBox="0 0 760 390" preserveAspectRatio="none" aria-label="Stylized service route map"><path className="road main-road" d="M-20 280 C120 245,190 330,310 255 S520 185,790 220"/><path className="road" d="M90 -20 C130 90,185 150,270 210 S380 320,435 420"/><path className="road" d="M540 -20 C500 75,515 120,585 170 S690 265,720 420"/><path className="road minor" d="M-20 100 C130 130,235 60,395 100 S600 125,790 70"/><path className="route-line route-a" d="M103 82 C165 120,157 195,248 214 S370 300,440 270"/><path className="route-line route-b" d="M342 91 C420 115,480 90,522 153 S595 240,678 277"/><path className="route-line route-c" d="M174 310 C240 270,285 275,330 333 S450 354,527 318"/></svg>
{[["DM","17%",31,53,"orange"],["SC","8%",67,38,"purple"],["JR","",42,76,"green"],["AP","",78,72,"yellow"]].map(([n,d,l,t,c])=><div key={n} className={`map-pin ${c}`} style={{left:`${l}%`,top:`${t}%`}}><span>{n}</span>{d&&<small>{d} late</small>}</div>)}<div className="map-label downtown">BOSTON</div><div className="map-label cambridge">CAMBRIDGE</div><div className="map-label quincy">QUINCY</div><div className="map-summary"><Navigation/><div><strong>Next optimization</strong><span>in 4 min 32 sec</span></div></div></div></article>
<aside className="panel decision-panel"><div className="panel-heading"><div><h2>Decision stream</h2><p>Autonomous actions and reviews</p></div><button aria-label="Decision options"><MoreHorizontal/></button></div><div className="decision-list">{incident&&<Decision icon={<AlertTriangle/>} title="Capacity disruption" time="Now" text="Technician T-274 reported unavailable. Seven stops require reassignment." action={()=>setReviewOpen(true)}/>}<Decision tone="purple" icon={<Route/>} title="Route rebalanced" time="9:42 AM" text="Moved 2 stops from T-208 to T-319. Estimated SLA impact +1.4%."/><Decision tone="green" icon={<Clock3/>} title="Delay contained" time="9:18 AM" text="Customer window preserved after a 34-minute service overrun."/><Decision tone="gold" icon={<Navigation/>} title="Travel optimized" time="8:51 AM" text="Sequencing change removed 11.8 projected miles across three routes."/></div><button className="view-log">View full decision log <ArrowRight/></button></aside></section>
<section className="panel roster-panel"><div className="panel-heading roster-heading"><div><h2>Technician fleet</h2><p>Live workload and route health</p></div><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search technician" aria-label="Search technician"/></label></div><div className="table-wrap"><table><thead><tr><th>Technician</th><th>Status</th><th>Specialty</th><th>Stops</th><th>Distance</th><th>Utilization</th></tr></thead><tbody>{visible.map(t=><tr key={t.id}><td><div className="tech"><span style={{background:t.color}}>{t.initials}</span><div><strong>{t.name}</strong><small>{t.id}</small></div></div></td><td><span className={`status ${t.status.replace(" ","-").toLowerCase()}`}>{t.status}</span></td><td>{t.specialty}</td><td>{t.stops}</td><td>{t.miles} mi</td><td><div className="util"><span><i style={{width:`${t.utilization}%`}}/></span><strong>{t.utilization}%</strong></div></td></tr>)}</tbody></table>{visible.length===0&&<div className="empty">No technicians match “{search}”.</div>}</div></section></div><RecoveryDialog open={reviewOpen} onOpenChange={setReviewOpen} onAccept={accept} plan={plan} weights={weights}/><PolicyDialog open={policyOpen} onOpenChange={setPolicyOpen} weights={weights} onChange={setWeights} plan={plan}/></section></main>}
function Decision({icon,title,time,text,tone="",action}:{icon:React.ReactNode;title:string;time:string;text:string;tone?:string;action?:()=>void}){return <div className="decision"><span className={`decision-icon ${tone}`}>{icon}</span><div><div className="decision-top"><strong>{title}</strong><time>{time}</time></div><p>{text}</p>{action?<button onClick={action}>Review recovery plan <ArrowRight/></button>:<span className="auto"><Check/> Executed automatically</span>}</div></div>}

function RecoveryDialog({open,onOpenChange,onAccept,plan,weights}:{open:boolean;onOpenChange:(open:boolean)=>void;onAccept:()=>void;plan:RecoveryPlan;weights:PolicyWeights}){
return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="recovery-dialog sm:max-w-[920px]">
<DialogHeader><div className="recovery-title-row"><span><BrainCircuit/></span><div><DialogTitle>Recovery plan RC-0912-04</DialogTitle><DialogDescription>Technician T-274 unavailable at 10:07 AM · 7 stops affected</DialogDescription></div><span className="confidence">{plan.confidence}% confidence</span></div></DialogHeader>
<div className="recovery-summary"><div><small>Preserved appointments</small><strong>{plan.assignments.length} of 7</strong><span>{plan.rescheduled.length} require rescheduling</span></div><div><small>Projected SLA</small><strong>{plan.projectedSla}%</strong><span>Plan score {plan.score} / 100</span></div><div><small>Added travel</small><strong>{plan.addedTravel} mi</strong><span>Across 3 routes</span></div><div><small>Overtime exposure</small><strong>{plan.overtime} hr</strong><span>{plan.overtime>.5?"Approval threshold exceeded":"Within policy limit"}</span></div></div>
<div className="recovery-body"><section><div className="section-title"><div><h3>Recommended reassignments</h3><p>Best of {plan.feasibleScenarios.toLocaleString()} feasible plans from {plan.scenariosEvaluated.toLocaleString()} evaluated</p></div><span>{plan.assignments.length} route changes</span></div><div className="move-list">{plan.assignments.map(move=><div className="move" key={move.jobId}><div><strong>{move.jobId}</strong><small>{move.window}</small></div><div className="job"><strong>{move.job}</strong><small>{move.from} <ArrowRight/> {move.to}</small></div><span>+{move.impactMinutes} min</span></div>)}</div>
<div className="customer-impact"><AlertTriangle/><div><strong>{plan.rescheduled.length} appointments cannot be preserved</strong><p>{plan.rescheduled.map(item=>item.id).join(" and ")} exceed qualified technician capacity. Earliest recovery windows are Saturday, 8:00–10:00 AM.</p></div><button>View customers</button></div></section>
<aside><div className="constraint-header"><ShieldCheck/><div><h3>Constraint validation</h3><p>All hard constraints passed</p></div></div>{["Technician certification","Shift availability","Service territory","Parts availability","Route capacity"].map(label=><div className="constraint" key={label}><Check/><span>{label}</span><strong>Passed</strong></div>)}<div className="policy-note"><small>Solver evidence</small><strong>{plan.rejectedCandidates} ineligible candidates excluded</strong><p>Invalid assignments are removed before weighted scoring. Human approval remains required for customer rescheduling.</p></div></aside></div>
<div className="audit-note"><span>Decision basis</span> SLA protection {weights.sla}% · travel efficiency {weights.travel}% · technician load {weights.load}% · overtime {weights.overtime}% · schedule stability {weights.stability}%</div>
<DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Reject plan</Button><Button variant="outline">Modify assignments</Button><Button onClick={onAccept} className="accept-plan"><Check/> Accept and execute</Button></DialogFooter>
</DialogContent></Dialog>}

function PolicyDialog({open,onOpenChange,weights,onChange,plan}:{open:boolean;onOpenChange:(open:boolean)=>void;weights:PolicyWeights;onChange:(weights:PolicyWeights)=>void;plan:RecoveryPlan}){
const controls:[keyof PolicyWeights,string,string][]=[
["sla","SLA protection","Prioritize appointments delivered inside the promised window"],
["travel","Travel efficiency","Reduce incremental route mileage"],
["load","Technician load","Balance capacity across eligible technicians"],
["overtime","Overtime reduction","Limit work extending beyond scheduled shifts"],
["stability","Schedule stability","Avoid customer rescheduling and route changes"]];
const total=Object.values(weights).reduce((sum,value)=>sum+value,0);
return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="policy-dialog sm:max-w-[620px]"><DialogHeader><DialogTitle>Optimization policy</DialogTitle><DialogDescription>Adjust business priorities. The solver normalizes weights automatically and recalculates the best feasible recovery plan.</DialogDescription></DialogHeader><div className="policy-score"><div><span>Current plan score</span><strong>{plan.score}</strong></div><div><span>Projected SLA</span><strong>{plan.projectedSla}%</strong></div><div><span>Raw weight total</span><strong>{total}</strong></div></div><div className="weight-controls">{controls.map(([key,label,description])=><div className="weight-control" key={key}><div><strong>{label}</strong><span>{weights[key]}%</span></div><p>{description}</p><Slider min={0} max={60} step={5} value={[weights[key]]} onValueChange={value=>onChange({...weights,[key]:value[0]})}/></div>)}</div><div className="solver-note"><BrainCircuit/><div><strong>Deterministic recomputation</strong><p>Every change reruns the bounded assignment search. Hard constraints remain non-negotiable and are never converted into weighted preferences.</p></div></div><DialogFooter><Button variant="outline" onClick={()=>onChange(defaultPolicyWeights)}>Restore defaults</Button><Button onClick={()=>onOpenChange(false)}>Apply policy</Button></DialogFooter></DialogContent></Dialog>}
